import { IconProp } from "@fortawesome/fontawesome-svg-core";
interface IInputProps {
    label?: string;
    labelInline?: boolean;
    labelClassName?: string;
    htmlFor?: string;
    register?: any;
    name?: string;
    defaultValue?: any;
    value?: any;
    validationError?: any;
    type?: string;
    onChange?: any;
    onClick?: any;
    onFocus?: any;
    onBlur?: any;
    onKeyPress?: any;
    onKeyUp?: any;
    step?: any;
    min?: number;
    max?: number;
    maxLength?: number;
    autoComplete?: any;
    disabled?: boolean;
    reference?: any;
    placeholder?: string;
    id?: string;
    containerClassName?: string;
    errorMessage?: string;
    autoFocus?: any;
    optional?: any;
    readOnly?: boolean;
    inputClassName?: string;
    info?: any;
    inputFieldId?: string;
    appendIcon?: IconProp;
    appendIconId?: string;
    onAppendIconClick?: any;
    appendIconColor?: string;
    appendText?: string;
    appendPadding?: string;
    appendSelectProps?: any;
    prependText?: string;
    prependPadding?: string;
    inputFieldStyle?: any;
    inputId?: string;
    onClearSearch?: Function;
    prependSelectProps?: any;
    prependTextSize?: string;
    showAsterisk?: boolean;
    noArrows?: boolean;
    disableNumericInputScroll?: boolean;
    pointer?: boolean;
    dataTest?: string | undefined;
}
declare function Input(props: IInputProps): JSX.Element;
export { Input };
